let possibleTypos = {};
possibleTypos["a"] = "qsw";
possibleTypos["b"] = "vnhj";
possibleTypos["c"] = "xgvf";
possibleTypos["d"] = "esyfsxr";
possibleTypos["e"] = "wdr32s";
possibleTypos["f"] = "dxrgct";
possibleTypos["g"] = "fchtvz";
possibleTypos["h"] = "gzjvbu";
possibleTypos["i"] = "78ukoj";
possibleTypos["j"] = "hubkni";
possibleTypos["k"] = "jlniom";
possibleTypos["l"] = "kmop";
possibleTypos["m"] = "nlk";
possibleTypos["n"] = "bkmj";
possibleTypos["o"] = "ilp8k";
possibleTypos["p"] = "9ol";
possibleTypos["r"] = "34etfd";
possibleTypos["s"] = "weayd";
possibleTypos["t"] = "45rzgf";
possibleTypos["u"] = "67zijh";
possibleTypos["v"] = "chbg";
possibleTypos["w"] = "2qsea";
possibleTypos["x"] = "yfcd";
possibleTypos["y"] = "dxs"
possibleTypos["z"] = "thu56g";
for (let t in possibleTypos) {
    possibleTypos[t] = possibleTypos[t].split("");
}
module.exports = possibleTypos;